stages:
  train:
    cmd: python train.py
    deps:
    - data
    - train.py
    params:
    - batch_size
    - learning_rate
    - num_epochs
    - optimizer
    outs:
    - model
    metrics:
    - metrics.yml:
        cache: false
    plots:
    - training_logs:
        cache: false

plots:
  acc_train_vs_test:
    x: step
    y: 
      training_logs/test_accuracy.tsv: test_accuracy
      training_logs/train_accuracy.tsv: train_accuracy
    data:
    - training_logs/test_accuracy.tsv
    - training_logs/train_accuracy.tsv
