stages:
  train:
    cmd: python train.py
    deps:
    - data
    - train.py
    params:
    - batch_size
    - learning_rate
    - num_epochs
    - optimizer
    outs:
    - model
    - training_logs
    - train_cm.csv
    - test_cm.csv
    metrics:
    - metrics.yml:
        cache: false
    plots:
      - train.jpg
      - test.jpg
