acc_train_vs_test:
  x: step
  y: 
    training_logs/scalars/test_accuracy.tsv: test_accuracy
    training_logs/scalars/train_accuracy.tsv: train_accuracy
    training_logs/scalars/train_accuracy.tsv: train_accuracy

