stages:
  copy:
    cmd: cp ../train_cm.csv new_cm.csv
    deps:
    - ../train_cm.csv
    outs:
    - new_cm.csv

plots:
  confusion_matrix_from_subdir:
      x: predicted 
      y: 
        ../test_cm.csv: actual
        new_cm.csv: actual
      template: confusion_normalized
      title: Confusion matrix but from subdir
        
